CREATE OR REPLACE TABLE staging.netsuite_customers
	COPY GRANTS AS
SELECT id,
	   altname,
	   isperson,
	   email,
	   NULLIF(LOWER(email), '')                                        AS normalized_email,
	   PHONE,
	   NULLIF(REGEXP_REPLACE(phone, '^1|\\+1\\s?|\\(|\\)|-|\\s', ''), '') AS normalized_phone_number,
	   entityid,
	   firstname,
	   lastname,
	   firstorderdate,
	   firstsaledate,
	   LASTORDERDATE,
	   lastsaledate,
	   entitytitle,
	   category,
	   companyname,
	   CUSTENTITY_BOOMI_EXTERNALID,
	   CUSTENTITY_BOOMI_SOURCE,
	   DATECREATED,
	   DEFAULTBILLINGADDRESS,
	   DEFAULTSHIPPINGADDRESS,
	   custentityam_primary_sport as primary_sport,
     custentityam_secondary_sport as secondary_sport,
     custentityam_tertiary_sport as tertiary_sport,
     custentityam_tier as tier,
     custentityam_doors as doors,
     custentityam_buyer_name as buyer_name,
     custentityam_buyer_email as buyer_email,
     custentityam_pop as pop,
     custentityam_logistics as logistics,
     custentityam_city_1 as city_1,
     custentityam_city_2 as city_2,
     custentityam_city_3 as city_3,
     custentityam_state_1 as state_1,
     custentityam_state_2 as state_2,
     custentityam_state_3 as state_3,
	   duplicate,
	   _FIVETRAN_DELETED
FROM netsuite.customer
where _FIVETRAN_DELETED != true

