SELECT
  location::text,
  invoice::text,
  detailed_carrier::text,
  account_number::text,
  COALESCE(
    TRY_TO_DATE(BILLED_DATE, 'YYYY-MM-DD'),
    TRY_TO_DATE(BILLED_DATE, 'MM/DD/YYYY HH:MI:SS AM'),
    TRY_TO_DATE(BILLED_DATE, 'MM/DD/YYYY')
  ) AS billed_date_converted,
  order_number_wms::text,
  shipment_tracking_number::text,
  customer_name::text,
  COALESCE(
    TRY_TO_DATE(ship_DATE, 'YYYY-MM-DD'),
    TRY_TO_DATE(ship_DATE, 'MM/DD/YYYY HH:MI:SS AM'),
    TRY_TO_DATE(ship_DATE, 'MM/DD/YYYY')
  ) AS ship_DATE_converted,
  destination_address_1::text,
  destination_city::text,
  destination_state::text,
  destination_zip::text,
  destination_country::text,
  shipping_method::text,
  stord_service_level::text,
  sum_package_weight::text,
  zone::text,
  duties_charge,
  ancillary_charges_2,
  fuel_charges,
  residential_charges,
  shipping_charges,
  total_shipping_less_duties
FROM
  stord_invoices.parcel_details
union all 
 SELECT
      origin_facility AS location,
      'las_20241007' AS invoice,
      carrier AS detailed_carrier,
      NULL AS account_number,
      billed_date,
      order_number AS order_number_wms,
      tracking_number AS shipment_tracking_number,
      customer_name,
      ship_date,
      destination_address AS destination_address_1,
      final_destination_city AS destination_city,
      final_destination_state AS destination_state,
      final_destination_zip AS destination_zip,
      final_destination_country AS destination_country,
      NULL AS shipping_method,
      stord_service_level,
      weight_in_ounces AS sum_package_weight,
      zone,
      duty duties_charge,
      other AS ancillary_charges_2,
      fuel fuel_charges,
      residential residential_charges,
      NULL AS shipping_charges,
      total_cost AS total_shipping_less_duties
    FROM
      stord_invoices.las_20241007
   union all 
  select  
     origin_facility AS location,
      'INV6027590' AS invoice,
      carrier AS detailed_carrier,
      NULL AS account_number,
      billed_date,
      order_number AS order_number_wms,
      tracking_number AS shipment_tracking_number,
      customer_name,
      ship_date,
      destination_address AS destination_address_1,
      final_destination_city AS destination_city,
      final_destination_state AS destination_state,
      final_destination_zip AS destination_zip,
      final_destination_country AS destination_country,
      NULL AS shipping_method,
      stord_service_level,
      weight_in_ounces AS sum_package_weight,
      zone::text,
      duty duties_charge,
      other AS ancillary_charges_2,
      fuel fuel_charges,
      residential residential_charges,
      NULL AS shipping_charges,
      total_cost AS total_shipping_less_duties
  from stord_invoices.inv6027590