select
    EMAIL
     , FIRST_NAME
     , LAST_NAME
     , POINTS_EARNED
     , POINTS_BALANCE
     , REFERRAL_LINK
     , REFERRED_BY
     , LAST_SEEN
     , VIP_TIER
     , BIRTH_MONTH
     , BIRTH_DAY
     , BIRTH_YEAR
     , ANNIVERSARY_MONTH
     , ANNIVERSARY_DAY
     , ANNIVERSARY_YEAR
     , PLATFORM_ACCOUNT_CREATED_AT
     , CREATED_AT
     , PHONE_NUMBER
     , LOYALTY_ELIGIBLE
     , OPT_IN_DATE
     , REFERRAL_DISCOUNT_CODE
from
    YOTPO_EXPORTS.CUSTOMER_REPORT_010125_021225
UNION ALL
select
    EMAIL
     , FIRST_NAME
     , LAST_NAME
     , POINTS_EARNED
     , POINTS_BALANCE
     , REFERRAL_LINK
     , REFERRED_BY
     , LAST_SEEN
     , VIP_TIER
     , BIRTH_MONTH
     , BIRTH_DAY
     , BIRTH_YEAR
     , ANNIVERSARY_MONTH
     , ANNIVERSARY_DAY
     , ANNIVERSARY_YEAR
     , PLATFORM_ACCOUNT_CREATED_AT
     , CREATED_AT
     , PHONE_NUMBER
     , LOYALTY_ELIGIBLE
     , OPT_IN_DATE
     , REFERRAL_DISCOUNT_CODE
from
    YOTPO_EXPORTS.CUSTOMER_REPORT_120124_123124