-- SELECT
--   concat(
--     'AMEX',
--     TO_VARCHAR(LAST_DAY(TO_DATE(DATE, 'MM/DD/YYYY'), 'MONTH'), 'MMDDYYYY')
--   ) || LPAD(
--     ROW_NUMBER() OVER (
--       ORDER BY
--         DATE
--     ),
--     3,
--     '0'
--   ) AS external_id,
--   appears_on_your_statement_as,
--   clean_merchant as memo,
--   DATE,
--   amount,
--   Vendor,
--   GL,
--   Internal,
--   Description line_memo,
--   Department,
--   Department_id,
-- FROM
--   cleaned_list
--   LEFT OUTER JOIN google_sheets.amex_mapping map ON upper(map.vendor) = upper(cleaned_list.clean_merchant)

select * from fact.credit_card_merchant_map where source='AMEX' and card_member = 'JANE WU'