SELECT
  shipmentnumber,
  item,
  expectedrate,
  quantitybilled,
  quantityexpected,
  quantityreceived,
  quantityremaining,
  receivinglocation,
  shipmentitemamount,
  totalunitcost,
  unitlandedcost
FROM
  fact.inbound_shipment_item_detail