/*
This SQL query is designed to retrieve and aggregate data from the TIKTOK_ADS.CAMPAIGN_REPORT_DAILY table.
The purpose of this query is to provide insights into campaign performance metrics such as spend,
revenue, impressions, clicks, and conversions.

Parameters:
- None

Return Value:
- event_date: The date of the campaign performance metrics.
- campaign_id_tiktok: The unique identifier of the TikTok campaign.
- spend: The total amount spent on the campaign.
- revenue: The total revenue generated from the campaign.
- impressions: The total number of impressions received by the campaign.
- clicks: The total number of clicks generated by the campaign.
- conversions: The total number of conversions achieved by the campaign.

The query groups the results by event_date and campaign_id_tiktok, and orders the results by event_date in ascending order.

Used downstream in the performance_media table

Base table: CTE root_table is used to get root table reference for scheduling in mozart.
If no longer a base table, then remove CTE root_table.
*/

with root_table as (
    select
      *
    from
      mozart.pipeline_root_table
)

select
    date(crd.stat_time_day)                                    as event_date
  , crd.campaign_id                                            as campaign_id_tiktok
  , sum(crd.spend)                                             as spend
  , sum(crd.complete_payment * crd.value_per_complete_payment) as revenue
  , sum(crd.impressions)                                       as impressions
  , sum(crd.clicks)                                            as clicks
  , sum(crd.conversion)                                        as conversions
  , sum(crd.reach)                                             as reach
from
    tiktok_ads.campaign_report_daily crd
group by
    date(crd.stat_time_day)
  , crd.campaign_id
order by
    date(crd.stat_time_day)