SELECT LISTAGG(
    'SELECT
      ''' || COLUMN_NAME || ''' AS ColumnName,
      ''' || DATA_TYPE || ''' AS Datatype,
      COUNT(*) AS TotalRows,
      SUM(CASE WHEN ' || COLUMN_NAME || ' IS NULL THEN 1 ELSE 0 END) AS NullCount,
      COUNT(*) - COUNT(DISTINCT ' || COLUMN_NAME || ') AS DuplicateCount
    FROM ' || 'ONE_OFF_REQUESTS.LAUNCH_SALES_BY_SKU',
    ' UNION ALL '
  ) WITHIN GROUP (ORDER BY COLUMN_NAME)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'ONE_OFF_REQUESTS' AND TABLE_NAME = 'LAUNCH_SALES_BY_SKU'